### ISSUE TITLE
Sort templates by rank

### ISSUE THREAD

**Issue by joshkh** [intermine/bluegenes#129]
Courtesy of @julie-sullivan :

"I just added rank to the template JSON"

```
"name":"AllGene_Chromosome",
         "comment":"",
         "tags":[  
            "im:aspect:Genes",
            "im:public"
         ],
         "rank":"2",
```

**Comment by yochannah** [comment]
Templates folder: https://github.com/intermine/bluegenes/tree/dev/src/cljs/bluegenes/components/templates

**Comment by danielabutano** [comment]
@yochannah I have tried to fixed it with no success. Here my small change https://github.com/danielabutano/bluegenes/commit/fc0d7cd5b34591a51b9cfe115df65e9e0ceaa680
Note: I have used the field name insted of rank because it's simpler to test

**Comment by yochannah** [comment]
@danielabutano I've taken a quick look. It's a great start! The reason it's not sorting is because you're to sort something on a property that's nested really deeply. 

To see what was going on, I copied your sorted data (on line 66 of the code you linked) and logged it to the console, like this:

```clojure
     (.log js/console "Sorted templates:" (clj->js (sort-by :name (filter (partial template-contains-string? text-filter) (filter filter-fn templates)))))
```

Looking at the data structure we're working with, you have a vector with the programmatic name of the template and the values inside the template - see 

![image](https://user-images.githubusercontent.com/9271438/45157604-88721e80-b1d9-11e8-9080-05b2d138f7aa.png)

`:rank` and `:name` are still there, but nested inside the map that is the second option in the vector. We need to go deeper to access it.

![image](https://user-images.githubusercontent.com/9271438/45157965-747aec80-b1da-11e8-94ae-644c669e77e6.png)

========================================

Here's a simpler example: 

```clojure
;; What you are trying to do: 
(def my-templates [{:name "eve"} {:name "bob"} {:name "alice"}])
(sort-by :name my-templates)
;; Returns: ({:name "alice"} {:name "bob"} {:name "eve"})
```
What it's doing behind the scenes is it's running the function `:name` on every element of the list and uses the result to sort the elements, e.g. `(:name {:name "eve"})` returns `eve` and `(:name {:name "bob"})` returns bob, and then it runs an alphabetic sort on the results.


The problem is that the data structure in the templates looks more like this in reality: 

```clojure
(def my-templates 
    [["Eve" {:name "eve"}] 
    ["Bob" {:name "bob"}] 
    ["Alice" {:name "alice"}]])
(sort-by :name my-templates)
```

Again, this runs the function `:name` on every element of the list and uses the result to sort the elements, e.g. 

```clojure
(:name ["Eve" {:name "eve"}])
```

Try this in your repl - this returns `nil`, since the vector `["Eve" {:name "eve"}]` doesn't have a property called `:name` to return, hence why the data are never sorted. 

To sort the simple example by name, I could do this:

```clojure
(def my-templates 
    [["Eve" {:name "eve"}] 
    ["Bob" {:name "bob"}] 
    ["Alice" {:name "alice"}]])
(sort-by first my-templates)
```

This produces the output we want, as it's getting the first element in each vector e.g. `(first ["Eve" {:name "eve"}])` - so it's grabbing "Eve" and "Bob" and "Alice", rather than the maps that are the second elements. This won't be any good if we want to sort on any of the nested properties in the map! To do that, we'll have to pass a custom function, rather than using `first` or `:name`.

So, let's try again: 

```clojure
(def my-templates 
    [["Eve" {:name "eve"}] 
    ["Bob" {:name "bob"}] 
    ["Alice" {:name "alice"}]])

(sort-by 
    (fn [[template-name template-details]] 
        (:name template-details)) 
my-templates)
```

Let me know if that makes sense, or I can help walk you through applying it to the templates scenario if needed.
