### ISSUE TITLE
query builder: allow filtering by subclass

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/bluegenes#508]
for a certain class, allow to filter according to subclasses.
for example, when querying sequenceFeature, you may want to filter by subclasses (for example in the summary box, or in the class constraint)

**Comment by heralden** [comment]
This is partially implemented (the subclass constraint is available on some, although the list of subclasses is incomplete).

Note to self: See https://github.com/intermine/bluegenes/issues/459#issuecomment-644042668 for an approach. To fix this issue, we will have to ask for the `descendants` of the class (acquired using `imcljs.path/class` on the path) in the hierarchy. We might also have to remove `(conj subclasses (:referencedType properties))` since this doesn't seem to always match the subclasses available for filtering in the old webapp (verify this).

Edit: Including referencedType in the dropdown of subclasses is appropriate due to the interface being different from the old webapp. In the old webapp, you would activate the dropdown for a subclass only when you wanted to constrain for a subclass. In Bluegenes, the dropdown will always be visible (defaulting to the class itself) and only used to constrain to a subclass when changing to them in the dropdown.
